INSERT INTO products VALUES
(
    101, 
    'Salad', 
    'https://cdn.loveandlemons.com/wp-content/uploads/2021/04/green-salad.jpg',
    60,
    'MDL'
),
(
    102, 
    'Soup', 
    'https://www.inspiredtaste.net/wp-content/uploads/2018/10/Homemade-Vegetable-Soup-Recipe-2-1200.jpg',
    40,
    'MDL'
),
(
    103, 
    'Cappuccino', 
    'https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcRWm9qKkP2EkvSnBuwhWD7T8-oRTUNKZFq13dgEowlcT4Kqymc2bv4b0ZzJXv0aT4wR',
    10,
    'MDL'
);